
services:
  web: 
    build: .
    volumes:
      - ./:/usr/src 
    working_dir: /usr/src
    command: sh -c 'alembic upgrade head && cd app && python __main__.py'
    networks:
      - app-network
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - database

  database:
    image: postgres:latest
    container_name: postgres-container
    restart: always
    volumes:
      - .postgres:/var/lib/postgres/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - app-network
    ports:
      - '5432:5432'

networks:
  app-network:
    external: true
